{"uuid": "95185f08-5d83-4895-9004-f0a93c06fa16", "children": ["846eee4c-0914-45e2-80a5-12ff1ccc6c50"], "befores": [{"name": "environment_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\Subhashini\\PycharmProjects\\python\\Allureworking\\test_MouseKeyboardop.py\", line 12, in environment_setup\n    driver=Chrome(executable_path=path)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1594200376983, "stop": 1594200376983}], "start": 1594200376983, "stop": 1594200377160}