{"uuid": "fe2c5224-202c-481a-9d8c-6ebad7d0d3d9", "children": ["4e97915c-027d-4f40-ad41-ef2fc219fab7"], "befores": [{"name": "environment_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\Subhashini\\PycharmProjects\\python\\Allureworking\\test_keyboard.py\", line 12, in environment_setup\n    driver=Chrome(executable_path=path)\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\subhashini\\pycharmprojects\\python\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1594200377176, "stop": 1594200377176}], "start": 1594200377176, "stop": 1594200377301}